---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: rancher-saas-ops
  name: rancher-saas-ops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rancher-saas-ops
subjects:
- kind: ServiceAccount
  name: rancher-saas-ops
  namespace: {{ .Values.namespace }}
