apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deploy-api
  {{- if .Values.ingress.letsEncrypt.enabled }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  {{- end }}
spec:
  rules:
  - host: "{{ .Values.ingress.deployAPIHost }}.{{ .Values.ingress.domain }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: deploy-api
            port:
              number: 9000
  tls:
    - hosts:
      - "{{ .Values.ingress.deployAPIHost }}.{{ .Values.ingress.domain }}"
      {{- if .Values.ingress.letsEncrypt.enabled }}
      secretName: deploy-api-tls-letsencrypt
      {{- else }}
      secretName: {{ .Values.ingress.TLSsecretName }}
      {{- end }}