---
apiVersion: v1
kind: Service
metadata:
  name: start-api
spec:
  selector:
    app: rancher-saas-ops
    role: start-api
  ports:
  - name: hattp
    protocol: TCP
    port: 9000
    targetPort: 9000