# Default values for Rancher SaaS API.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

timezone: "Europe/Zurich"
namespace: rancher-saas-ops

image:
  repository: harbor.apps.lab.onzack.io/rancher-saas/rancher-saas-ops
  tag: v0.1.19
  imagePullSecret: REDACTED

deployAPI:
  replicas: 3
  requests:
    memory: 100Mi
    cpu: 50m
  limits:
    memory: 1Gi
    cpu: 500m

updateAPI:
  replicas: 3
  requests:
    memory: 100Mi
    cpu: 50m
  limits:
    memory: 1Gi
    cpu: 500m
  
token: REDACTED
rancherClusterID: REDACTED
rancherProjectID: REDACTED  
environmentValuesFile: /etc/rancher-saas/environment.yaml

ingress:
  letsEncrypt:
    enabled: false
  # Domain for ingress host, added to instanceName
  deployAPIHost: deploy-api
  updateAPIHost: update-api
  domain: example.com
  # TLS key and cert for the ingress tls secret -> needed if letsEncrypt is disabled
  TLSsecretName: custom-ingress-tls
  # TLSkey: REDACTED
  # TLScert: REDACTED
  # CAcert: REDACTED