---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: rancher-saas-api
  name: rancher-saas-api
rules:
- apiGroups:
  - ""
  - apps
  - networking.k8s.io
  resources:
  - namespaces
  - statefulsets
  - services
  - secrets
  - ingresses
  - networkpolicies
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
