{{- if eq .Values.ingress.letsEncrypt.enabled false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.secretName }}
type: kubernetes.io/tls
stringData:
  tls.crt: |
        {{ .Values.ingress.TLScert }}
  tls.key: |
        {{ .Values.ingress.TLSkey }}
{{- end }}