{{- if eq .Values.ingress.letsEncrypt.enabled false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.CAname }}
type: Opaque
data:
  cacerts.pem: |
        {{ .Values.ingress.CAcert }}
{{- end }}