{{- if .Values.rancherGuard.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rancher-guard-{{ .Values.rancher.instanceName }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.rancherGuardSize }}
  storageClassName: {{ .Values.storage.storageClassName }}
{{- end }}