apiVersion: v1
kind: Service
metadata:
  name: rancher
spec:
  selector:
    app: rancher
    role: server
  ports:
  - name: hattp
    protocol: TCP
    port: 80
    targetPort: 80
  - name: hattps
    protocol: TCP
    port: 443
    targetPort: 443